ALTER TABLE [dbo].[BookAuthor]
    ADD CONSTRAINT [PK_BookAuthor] PRIMARY KEY CLUSTERED ([BookID] ASC, [AuthorID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

